### ISSUE TITLE
Change licence to Creative Commons Attribution 4.0? (Apache requires the full text of the license to appear in the document)

### ISSUE THREAD

**Issue by kairoswater-jason** [flavio20002/typst-orange-template#16]
The Apache license requires the full license text to be reproduced in the documents generated using this template.

I like this template, but probably won't be able to use it due to the above.

Would you consider switching the project to: https://creativecommons.org/licenses/by/4.0/ ? The creative commons attribution license just requires appropriate credit to be given and a link to the CC license in the document.

**Comment by flavio20002** [comment]
Done, I've used the same license of the original template for Latex

**Comment by kairoswater-jason** [comment]
Bummer! (Noncommercial)

**Comment by flavio20002** [comment]
Why? You can sell a book made with this template, but you can't sell the template itself.

**Comment by kairoswater-jason** [comment]
Maybe I'm being too cautious.

Original I was not entirely convinced that the license would permit commercial use, such as a book being sold, without violating the terms in certain jurisdictions.

The license says that the user can:
[1] "produce, reproduce, and Share Adapted Material for NonCommercial purposes only."

I worry that the generated PDF could be considered an Adapted Material 

What is adapted material?


>  [2] Section 1 – Definitions.
> 
>     Adapted Material means material subject to Copyright and Similar Rights that is derived from or based upon the Licensed Material and in which the Licensed Material is translated, altered, arranged, transformed, or otherwise modified in a manner requiring permission under the Copyright and Similar Rights held by the Licensor...

If I'm reading the license [2] correctly, the generated output of the template (eg. a PDF) could be considered:
1. To be "derived from or based upon" the licensed work
- Portions of the PDF generating using template seemed to be at least partially derived from the template
2. And to contain "arranged or transformed" portions of the "Licensed Material"
-  Portions of the PDF are transformed versions template and arranged by the user (this applies even when ignoring any media like supplied images, fonts, etc.)
- For example source code run through a compiler is transformed into a binary. The binary contains information encoded in the source. Typst interpreting the template and producing a PDF is a transformation and arrangement.
3. And <item from 2> is used "in a manner requiring permission under the Copyright and Similar ..."
- Item 3 is the only questionable item for me. I suppose you could be right. It could be argued that the transformed work is modified so much that you might have no copyright claim on the small derived/transformed/arranged portions of the generated PDF/book/etc.

I don't know for sure. I suppose the LaTeX version of the template probably got used commercially under this license.

**Comment by flavio20002** [comment]
The problem is that this template is the Latex one rewritten in Typst. So I can't use a license that is more open that the original one. 
Read this:
https://latex.org/forum/viewtopic.php?t=31789

Hi Rajiv,

The license applies to the templates themselves. What I mean by this is that the templates cannot be used commercially via selling them directly or as adding value to a service/package of a commercial nature.

It is ok to take a template and make a derivative work by, for example, writing a book and then selling the resulting document (PDF) only, provided there is attribution for the template used. Note that the template used to create the document (the .tex files) cannot be sold or used commercially which shouldn’t be a problem since I imagine you will be selling the PDF version of the book only. Attribution will be required and you can use any text you like provided there is a mention of “LaTeXTemplates.com” somewhere.

Essentially, the point of the license is to enable people to freely download, modify and redistribute templates but always attribute them back to LaTeXTemplates.com as the source. Not allowing commercial use keeps the templates effectively owned by this website and means this will always be the one “true” source of them.

Have a read of this page for more information on the Creative Commons license.

I hope that cleared things up for you, if not, send me an email.

Cheers,
Vel
